export const DEFAULT_DESIGN_SYSTEM = {
  id: 'default',
  name: '默认教学风格',
  tokens: {
    colors: {
      primary: '#2563eb',
      secondary: '#7c3aed',
      success: '#22c55e',
      warning: '#f59e0b',
      danger: '#ef4444',
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#1e293b',
      textMuted: '#64748b',
      border: '#e2e8f0',
      accent: '#3b82f6',
    },
    fonts: {
      heading: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
      body: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
      mono: '"JetBrains Mono", "Fira Code", monospace',
    },
    fontSizes: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 18,
      xl: 24,
      '2xl': 32,
      '3xl': 40,
      '4xl': 56,
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 16,
      lg: 24,
      xl: 32,
      '2xl': 48,
    },
    borderRadius: {
      sm: 4,
      md: 8,
      lg: 12,
      xl: 16,
      full: 9999,
    },
    shadows: {
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
    },
  },
};

export const DESIGN_THEMES: Record<string, typeof DEFAULT_DESIGN_SYSTEM> = {
  academic: {
    id: 'academic',
    name: '学术蓝',
    tokens: {
      colors: {
        primary: '#2563eb',
        secondary: '#06b6d4',
        success: '#22c55e',
        warning: '#f59e0b',
        danger: '#ef4444',
        background: '#ffffff',
        surface: '#f0f7ff',
        text: '#0f172a',
        textMuted: '#475569',
        border: '#dbeafe',
        accent: '#3b82f6',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(37 99 235 / 0.15)',
        lg: '0 20px 25px -5px rgb(37 99 235 / 0.2)',
      },
    },
  },
  humanities: {
    id: 'humanities',
    name: '人文暖',
    tokens: {
      colors: {
        primary: '#92400e',
        secondary: '#b45309',
        success: '#15803d',
        warning: '#d97706',
        danger: '#dc2626',
        background: '#fffbf5',
        surface: '#fff7ed',
        text: '#451a03',
        textMuted: '#78350f',
        border: '#fed7aa',
        accent: '#c2410c',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(146 64 14 / 0.12)',
        lg: '0 20px 25px -5px rgb(146 64 14 / 0.18)',
      },
    },
  },
  language: {
    id: 'language',
    name: '活力紫橙',
    tokens: {
      colors: {
        primary: '#7c3aed',
        secondary: '#f97316',
        success: '#22c55e',
        warning: '#eab308',
        danger: '#ef4444',
        background: '#ffffff',
        surface: '#f5f3ff',
        text: '#2e1065',
        textMuted: '#6b21a8',
        border: '#ddd6fe',
        accent: '#f97316',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(124 58 237 / 0.15)',
        lg: '0 20px 25px -5px rgb(124 58 237 / 0.22)',
      },
    },
  },
  tech: {
    id: 'tech',
    name: '深色科技',
    tokens: {
      colors: {
        primary: '#38bdf8',
        secondary: '#818cf8',
        success: '#4ade80',
        warning: '#facc15',
        danger: '#fb7185',
        background: '#0f172a',
        surface: '#1e293b',
        text: '#f8fafc',
        textMuted: '#94a3b8',
        border: '#334155',
        accent: '#22d3ee',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.3)',
        md: '0 8px 16px -4px rgb(56 189 248 / 0.2)',
        lg: '0 20px 25px -5px rgb(56 189 248 / 0.3)',
      },
    },
  },
  chinese: {
    id: 'chinese',
    name: '国风青黛',
    tokens: {
      colors: {
        primary: '#1B3A6B',
        secondary: '#8B4513',
        success: '#15803d',
        warning: '#d97706',
        danger: '#dc2626',
        background: '#FFFEF5',
        surface: '#FDF6E3',
        text: '#1a1a1a',
        textMuted: '#5D4E37',
        border: '#E8DCC4',
        accent: '#C0392B',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(27 58 107 / 0.12)',
        lg: '0 20px 25px -5px rgb(27 58 107 / 0.18)',
      },
    },
  },
  math: {
    id: 'math',
    name: '理性几何',
    tokens: {
      colors: {
        primary: '#2C3E50',
        secondary: '#7F8C8D',
        success: '#27AE60',
        warning: '#F39C12',
        danger: '#E74C3C',
        background: '#FFFFFF',
        surface: '#F0F3F4',
        text: '#1C2833',
        textMuted: '#5D6D7E',
        border: '#D5DBDB',
        accent: '#27AE60',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(44 62 80 / 0.12)',
        lg: '0 20px 25px -5px rgb(44 62 80 / 0.18)',
      },
    },
  },
  english: {
    id: 'english',
    name: '活力紫橙',
    tokens: {
      colors: {
        primary: '#8E44AD',
        secondary: '#BDC3C7',
        success: '#22c55e',
        warning: '#F39C12',
        danger: '#ef4444',
        background: '#F8F9FA',
        surface: '#F5EEF8',
        text: '#2E1065',
        textMuted: '#6B21A8',
        border: '#D7BDE2',
        accent: '#F39C12',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(142 68 173 / 0.15)',
        lg: '0 20px 25px -5px rgb(142 68 173 / 0.22)',
      },
    },
  },
  science: {
    id: 'science',
    name: '科学探索',
    tokens: {
      colors: {
        primary: '#1B3A6B',
        secondary: '#2980B9',
        success: '#27AE60',
        warning: '#F1C40F',
        danger: '#E74C3C',
        background: '#EBF5FB',
        surface: '#D6EAF8',
        text: '#154360',
        textMuted: '#2471A3',
        border: '#AED6F1',
        accent: '#1ABC9C',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(41 128 185 / 0.15)',
        lg: '0 20px 25px -5px rgb(41 128 185 / 0.22)',
      },
    },
  },
  history: {
    id: 'history',
    name: '文史琥珀',
    tokens: {
      colors: {
        primary: '#7F3C1C',
        secondary: '#A04000',
        success: '#15803d',
        warning: '#F1C40F',
        danger: '#C0392B',
        background: '#FDF2E9',
        surface: '#FAE5D3',
        text: '#4A235A',
        textMuted: '#873600',
        border: '#EDBB99',
        accent: '#F1C40F',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(127 60 28 / 0.12)',
        lg: '0 20px 25px -5px rgb(127 60 28 / 0.18)',
      },
    },
  },
  geography: {
    id: 'geography',
    name: '地理湖蓝',
    tokens: {
      colors: {
        primary: '#2471A3',
        secondary: '#2E86C1',
        success: '#27AE60',
        warning: '#F1C40F',
        danger: '#E74C3C',
        background: '#EBF5FB',
        surface: '#D6EAF8',
        text: '#1B4F72',
        textMuted: '#2E86C1',
        border: '#AED6F1',
        accent: '#1ABC9C',
      },
      fonts: DEFAULT_DESIGN_SYSTEM.tokens.fonts,
      fontSizes: DEFAULT_DESIGN_SYSTEM.tokens.fontSizes,
      spacing: DEFAULT_DESIGN_SYSTEM.tokens.spacing,
      borderRadius: DEFAULT_DESIGN_SYSTEM.tokens.borderRadius,
      shadows: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 8px 16px -4px rgb(36 113 163 / 0.15)',
        lg: '0 20px 25px -5px rgb(36 113 163 / 0.22)',
      },
    },
  },
};

export const COURSEWARE_VERSION = '1.0';

export const DEFAULT_SLIDE_SIZE = {
  width: 1280,
  height: 720,
};

export const SUPPORTED_DOCUMENT_TYPES = [
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'text/markdown',
  'text/plain',
  'image/png',
  'image/jpeg',
  'image/webp',
];
